### ISSUE TITLE
Local transcription does not work on mac

### ISSUE THREAD

**Issue by Carsonthemonkey** [Carsonthemonkey/GIST#93]
I think it can't find the path to the ffmpeg binary. It also may be an issue with how the python executable is built.

**Comment by Carsonthemonkey** [comment]
Running the command mentioned in [this](https://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/) article seems to stop the dmg is damaged error from occurring. This probably has to do with code signing, so this command is really a temporary solution.

**Comment by Carsonthemonkey** [comment]
After using the `xattr -cr <filepath>` command, I can run the app on another mac. However, local transcription will not get past the preprocessing stage. After digging into the app contents, and running local_whisper directly from the command line, I get the following error: 
```Traceback (most recent call last):
File "urilib/request.py", line 1348, in do_open File "http/client.py", line 1283, in request
File "http/client.py", line 1329, in _send_request
ioL
let
File "http/client.py", line 1278, in endheaders File "http/client.py", line 1038, in _send_output
File "http/client-py", line 976, in send
File "http/client.py", line 1455, in connect
File "ssl.py", line 517, in wrap_socket
riot
File "ssl.py", line 1075, in _create
son
File "ssl.py", line 1346, in do_handshake
ssI.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY FAILED] certificate verify failed: unable to get local issuer certificate son s1.c: 1002)
Pa During handling of the above exception, another exception occurred:
spa Traceback (most recent call last);
File "local_whisper.py", line 24, in <module>
nto
ch:
gP:
File "whisper/ init_ _•py", line 131, in load_ model File "whisper/__init_py", line 67, in _download File "urilib/request.py", line 216, in urlopen
File
"urilib/request.py", line 519, in open
File "urllib/request.py", line 536, in _open
File "urllib/request.py", line 496, in _call_chain
ans
File "urIlib/request.py", line 1391, in https_open File "urllib/request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certifi cate (_ss1. c: 1002)>
(25524] Failed to execute script 'local_whisper' due to unhandled exception!```

This seems to be a code signing error, so I will need to better understand this.
